name: ipyigv
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - jupyterlab=3
    - scipy
    - pandas
    - matplotlib
    - ipyigv
    - pip:
        - igv_jupyterlab

